### GET ALL USERS (Összes felhasználó lekérése)

GET http://localhost:3000/users
Content-Type: application/json

### GET ALL USERS by id (Egy felhasználó lekérése ID alapján)

GET http://localhost:3000/users/1
Content-Type: application/json


### POST LOGGED USER (Bejelentkezés)

POST http://localhost:3000/users/login
Content-Type: application/json

{
    "email": "admin",
    "password": "admin"
}

### POST NEW USER (Felhasználó regisztrálása)

POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "admin",
    "email": "admin3",
    "password": "admin"
}

### PATCH USER DATA (Felhasználói adatok módosítása)

PATCH http://localhost:3000/users/profile
Content-Type: application/json

{
    "id": 1,
    "name": "admin1",
    "email": "admin4@gmail.com"
}

### PATCH USER PASSWORD (Jelszó módosítása)

PATCH http://localhost:3000/users/profile
Content-Type: application/json

{
    "id": 1,
    "oldPassword": "admin",
    "newPassword": "admin",
}